name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8   # Downgraded to version 1.0.8
  http: ^0.13.6              # Latest version
  flutter_dotenv: ^5.0.2     # For loading environment variables
  intl: ^0.17.0              # For date formatting
  flutter_gemini: ^3.0.0     # Custom dependency (if needed)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
